version: '3.8'

services:
  # 1. POSTGRES-TIETOKANTA (Käyttää jo olemassa olevaa dataa voluumin kautta)
  movie-db:
    image: postgres:16
    container_name: movie-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:?DB_USER is required}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD is required}
      POSTGRES_DB: ${DB_NAME:?DB_NAME is required}
    ports:
      - "5432:5432"
    volumes:
      - postgres_movie_data:/var/lib/postgresql/data

  # 2. NODE.JS BACKEND
  movie-backend:
    build: ./Backend
    container_name: movie-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - movie-db

  # 3. REACT FRONTEND
  movie-frontend:
    build: ./Frontend
    container_name: movie-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - movie-backend

volumes:
  postgres_movie_data:

