CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    favorites_public BOOLEAN NOT NULL DEFAULT TRUE,
    favorites_share_token UUID,
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username),
    CONSTRAINT users_favorites_share_token_key UNIQUE (favorites_share_token)
);

CREATE TABLE IF NOT EXISTS groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    owner_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT groups_owner_id_fkey
        FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_groups_owner_id
    ON groups(owner_id);

CREATE TABLE IF NOT EXISTS favorites (
    user_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    media_type VARCHAR(10) NOT NULL,
    tmdb_id INTEGER NOT NULL,
    CONSTRAINT favorites_pkey PRIMARY KEY (user_id, media_type, tmdb_id),
    CONSTRAINT favorites_media_type_check
        CHECK (media_type IN ('movie', 'tv')),
    CONSTRAINT favorites_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS group_members (
    group_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT group_members_pkey PRIMARY KEY (group_id, user_id),
    CONSTRAINT group_members_status_check
        CHECK (status IN ('member', 'pending', 'invited')),
    CONSTRAINT group_members_group_id_fkey
        FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT group_members_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS group_media (
    group_id INTEGER NOT NULL,
    tmdb_id INTEGER NOT NULL,
    media_type VARCHAR(10) NOT NULL,
    added_by INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT group_media_pkey PRIMARY KEY (group_id, media_type, tmdb_id),
    CONSTRAINT group_media_media_type_check
        CHECK (media_type IN ('movie', 'tv')),
    CONSTRAINT group_media_group_id_fkey
        FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT group_media_added_by_fkey
        FOREIGN KEY (added_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_group_media_added_by
    ON group_media(added_by);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    rating SMALLINT NOT NULL,
    review_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    media_type VARCHAR(10),
    tmdb_id INTEGER,
    CONSTRAINT reviews_rating_check
        CHECK (rating >= 1 AND rating <= 5),
    CONSTRAINT reviews_media_type_check
        CHECK (media_type IN ('movie', 'tv')),
    CONSTRAINT uq_reviews_user_media
        UNIQUE (user_id, media_type, tmdb_id),
    CONSTRAINT fk_reviews_users
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reviews_user_id
    ON reviews(user_id);